name: demo-app
namespace: a1helene
replicaCount: 2

image:
  repository: hbaydocker2/jumbalaya-image
  pullPolicy: IfNotPresent
  tag: V1.0.5

ingress:
  host: demo.local

storage:
  size: 1Gi

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
